Disable debugging, update conditions in test-lp.yml

diff --git a/.github/workflows/test-lp.yml b/.github/workflows/test-lp.yml
--- a/.github/workflows/test-lp.yml
+++ b/.github/workflows/test-lp.yml
@@ -29,11 +29,10 @@ jobs:
         if: success()
         # Check if maintenance is turned off
         run: |
-            cat test-lp-output.txt | grep -q 'Tests failed in test suite' && echo "{TEST_SUITE_ERRORS}=true" >> "$GITHUB_ENV" \
-            || echo "{TEST_SUITE_ERRORS}=false" >> "$GITHUB_ENV"
+            cat test-lp-output.txt | grep -q 'Tests failed in test suite' && echo "TEST_SUITE_ERRORS=true" >> "$GITHUB_ENV" \
+            || echo "TEST_SUITE_ERRORS=false" >> "$GITHUB_ENV"
       - name: Test condition
-        if: success() && ${{ env.TEST_SUITE_ERRORS == 'true' }}
-        # 'echo $?' returns with exit code 1
+        if: env.TEST_SUITE_ERRORS == 'true' && success()
         run: |
           echo "Test failures detected in test suite, check the output in earlier steps"
           exit 1
@@ -42,10 +41,10 @@ jobs:
         if: success()
         # Check if maintenance is turned off
         run: |
-            cat test-lp-output.txt | grep -q 'maintenance is turned off' && echo "{MAINTENANCE}=off" >> "$GITHUB_ENV" \
-            || echo "{MAINTENANCE}=on" >> "$GITHUB_ENV"
+            cat test-lp-output.txt | grep -q 'maintenance is turned off' && echo "MAINTENANCE=off" >> "$GITHUB_ENV" \
+            || echo "MAINTENANCE=on" >> "$GITHUB_ENV"
       - name: Test condition
-        if: success() && ${{ env.MAINTENANCE == 'off' }}
+        if: env.MAINTENANCE == 'off' && success()
         # Skip opening a PR if tests have not been run
         run: echo "Maintenance is turned off for one or more files"
       - name: Create Pull Request
