Remove tmate session, add check for capitalization and spaces

diff --git a/.github/workflows/test-lp.yml b/.github/workflows/test-lp.yml
--- a/.github/workflows/test-lp.yml
+++ b/.github/workflows/test-lp.yml
@@ -18,11 +18,21 @@ jobs:
         with:
           files: |
              **.md
+      - name: Check for capital letters or spaces in content directory
+        run: |
+          echo "Checking for capital letters or spaces in content directory paths..."
+
+          git diff --name-only origin/${{ github.base_ref }}...HEAD |
+            grep '^content/' |
+            grep -E '[A-Z]|[[:space:]]' && {
+              echo "❌ Found invalid file or directory names with capital letters or spaces in 'content/'"
+              exit 1
+            }
+
+          echo "✅ No capital letters or spaces found in 'content/' paths."
       - name: Install dependencies
         if: steps.changed-markdown-files.outputs.any_changed == 'true'
         run: pip install -r tools/requirements.txt
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
       - name: Run test suite for all changed .md files
         id: run-suite
         if: steps.changed-markdown-files.outputs.any_changed == 'true'
